--- 
phases: 
  build: 
    commands: 
      - "echo Build started on `date`"
      - "echo Building the Docker image..."
      - "docker build -t dipti9429/helloworld ."
      - "docker tag dipti9429/helloworld dipti9429/helloworld:latest"
  post_build: 
    commands: 
      - "echo Build completed on `date`"
  version: 0.1
